### ISSUE TITLE
The sample don't print the records.

### ISSUE THREAD

**Issue by tuxmaster5000** [nbuchwitz/nc_dnsapi#2]
Hello,
the sample will only print the pointers.

> [<nc_dnsapi.DNSRecord object at 0x7fc40bcccd30>, <nc_dnsapi.DNSRecord object at 0x7fc40bcccda0>, <nc_dnsapi.DNSRecord object at 0x7fc40bccce10>, <nc_dnsapi.DNSRecord object at 0x7fc40bccce80>,

**Comment by tuxmaster5000** [comment]
I have create an PR for it.
https://github.com/nbuchwitz/nc_dnsapi/pull/3

**Comment by nbuchwitz** [comment]
Thanks!

Closed by #3
