### ISSUE TITLE
Invalid record type: SSHFP

### ISSUE THREAD

**Issue by KizzyCode** [nbuchwitz/nc_dnsapi#6]
Apparently, the `DNSRecord`-class does not support `SSHFP` records, which are (now?) supported by netcup.

**Comment by nbuchwitz** [comment]
From a first glance it should be enough to extend the list in https://github.com/nbuchwitz/nc_dnsapi/blob/master/nc_dnsapi/__init__.py#L25. PR welcome :-)

**Comment by nbuchwitz** [comment]
I was fixes another thing and added the support while at it. Please check if #8 works for you.

**Comment by KizzyCode** [comment]
Yes; I actually did the same yesterday by hotpatching the installed package (I needed it for ansible) and as far as I can tell, this works perfectly 😊
